# Generated by Django 3.1 on 2021-03-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'ordering': ['properties_name'], 'verbose_name': 'Справочник характеристик', 'verbose_name_plural': 'Справочник характеристик'},
        ),
        migrations.AlterModelOptions(
            name='propertiesproducts',
            options={'verbose_name': 'Характеристики товаров', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_name'], 'verbose_name': 'Производители', 'verbose_name_plural': 'Производители'},
        ),
    ]
