# Generated by Django 3.1 on 2021-03-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210313_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('status', models.SmallIntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Отменен'), (4, 'Завершен')], default=1)),
                ('delivery', models.SmallIntegerField(choices=[(1, 'Самовывоз'), (2, 'Доставка')], default=1)),
                ('paid', models.SmallIntegerField(choices=[(1, 'Не оплачен'), (2, 'Оплачен')], default=1)),
                ('summa', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['currency_name'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'ordering': ['properties_name'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='propertiesproducts',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_name'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='сategory',
            options={'ordering': ['category_name'], 'verbose_name': 'Группа товара', 'verbose_name_plural': 'Группы товара'},
        ),
        migrations.AlterModelOptions(
            name='сountry',
            options={'ordering': ['country_name'], 'verbose_name': 'Страна производства', 'verbose_name_plural': 'Страны производства'},
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orders', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Товар')),
            ],
        ),
    ]
