# Generated by Django 3.1 on 2021-03-13 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20210313_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Бренд'),
        ),
    ]
