# Generated by Django 3.1 on 2021-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210313_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сategory',
            name='category_name',
            field=models.CharField(db_index=True, max_length=90, unique=True, verbose_name='Группы товара'),
        ),
    ]
