# Generated by Django 3.1 on 2021-03-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210313_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['artno', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
