# Generated by Django 3.1 on 2021-03-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210313_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subсategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='subсategory',
            name='sub_category_name',
            field=models.CharField(blank=True, db_index=True, max_length=90, null=True, unique=True, verbose_name='Подгруппы товара'),
        ),
    ]
