# Generated by Django 3.1 on 2021-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210313_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subсategory',
            name='sub_category_name',
            field=models.CharField(blank=True, db_index=True, max_length=90, null=True, verbose_name='Подгруппы товара'),
        ),
    ]
