# Generated by Django 3.1 on 2021-03-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210313_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='subсategory',
            name='category',
            field=models.ForeignKey(default=719, on_delete=django.db.models.deletion.CASCADE, to='products.сategory', verbose_name='Группы товара'),
        ),
        migrations.AlterField(
            model_name='subсategory',
            name='sub_category_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=90, null=True, verbose_name='Подгруппы товара'),
        ),
    ]
